title: Eollugii
subtitle: Be Developer
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://eollugii.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Blog
      url: /blog
    - text: Shop
      url : /shop/
    - text: About Me
      url: /about/
    - text: Contact Me
      url : /contact/
    - text: Styleguide
      url: /styleguide/
    

# Edit these details 

author_logo: profile.png
author: Eollugii
author_bio: I wanna Developer
author_email: "eollugii@gmail.com"
author_location: Korea
author_website_url: "http://eollugii.github.io"

author_work_experiences: 
            - company_name: 없음
              company_logo: google.png
              company_url: https://google.com
              designation: 프로 백수
              description: 나 회사 안다녀!
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: 국비 교육원
                college_url: https://www.google.com
                college_degree: 자바 웹 개발자 과정
                description: Java
                visibility: true

author_post_details:
              - post_title: 코딩 풀이
                post_info: 타 사이트에 있는 코딩 문제 풀이
                post_description: 잘 못해요...
                post_url: https://www.google.com
                visibility: true

# social links
#twitter_username: johndoe
github_username:  eollugii
#facebook_username: johndoe
#linkedin_username: johndoe
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments using disqus
disqus_shortname: sujay-kundu  

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# formspree (contact form)
formspree_email: eollugii@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_author_post_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
